from typing import Protocol, List, Any
from app.domain.models import ArticleAttributes


class RepositoryProtocol(Protocol):
    async def get_raw_article(self, file_key: str) -> dict: ...
    async def save_processed_article(self, article: ArticleAttributes) -> None: ...
    async def list_unprocessed_files(self) -> List[str]: ...
    async def exists_in_silver(self, article_id: str) -> bool: ...


class CleanerProtocol(Protocol):
    def clean_text(self, text: str) -> str: ...


class EmbedderProtocol(Protocol):
    def generate_embedding(self, text: str) -> List[float]: ...
